id: A4EF4AD7A
base_file: f73D3.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:52:14.535768
  last_modified_at: 2022-05-30 18:52:14.535771
