id: A4EF4AD7A
base_file: fA861.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:52:14.537173
  last_modified_at: 2022-05-30 18:52:14.537176
