id: A4EF4AD7A
base_file: f6290.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:52:14.534534
  last_modified_at: 2022-05-30 18:52:14.534538
