id: A4EF4AD7A
base_file: f5352.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:52:14.532570
  last_modified_at: 2022-05-30 18:52:14.532578
